# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fireflies.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'fireflies.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66ireflies.proto\x12\x07\x66irefly\"B\n\x0c\x46ireflyState\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x16\n\x0e\x66lash_interval\x18\x02 \x01(\x02\x12\x0e\n\x06is_lit\x18\x03 \x01(\x08\"-\n\x17SynchronizationResponse\x12\x12\n\nadjustment\x18\x01 \x01(\x02\x32[\n\x0f\x46ireflyObserver\x12H\n\x0bReportState\x12\x15.firefly.FireflyState\x1a .firefly.SynchronizationResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fireflies_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FIREFLYSTATE']._serialized_start=28
  _globals['_FIREFLYSTATE']._serialized_end=94
  _globals['_SYNCHRONIZATIONRESPONSE']._serialized_start=96
  _globals['_SYNCHRONIZATIONRESPONSE']._serialized_end=141
  _globals['_FIREFLYOBSERVER']._serialized_start=143
  _globals['_FIREFLYOBSERVER']._serialized_end=234
# @@protoc_insertion_point(module_scope)
