# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: simulation.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'simulation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10simulation.proto\x12\x07\x66irefly\"1\n\x13RegistrationRequest\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\"\\\n\x14RegistrationResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nstart_time\x18\x02 \x01(\x02\x12$\n\tneighbors\x18\x03 \x03(\x0b\x32\x11.firefly.Neighbor\"6\n\x0eNeighborUpdate\x12$\n\tneighbors\x18\x01 \x03(\x0b\x32\x11.firefly.Neighbor\"2\n\x08Neighbor\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04host\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\"B\n\x0cStatusUpdate\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x16\n\x0e\x66lash_interval\x18\x02 \x01(\x02\x12\x0e\n\x06is_lit\x18\x03 \x01(\x08\":\n\x14\x46lashIntervalRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x16\n\x0e\x66lash_interval\x18\x02 \x01(\x02\"\x07\n\x05\x45mpty2\x95\x01\n\x0fObserverService\x12I\n\x08Register\x12\x1c.firefly.RegistrationRequest\x1a\x1d.firefly.RegistrationResponse\"\x00\x12\x37\n\x0cUpdateStatus\x12\x15.firefly.StatusUpdate\x1a\x0e.firefly.Empty\"\x00\x32\x96\x01\n\x0e\x46ireflyService\x12\x46\n\x13ReportFlashInterval\x12\x1d.firefly.FlashIntervalRequest\x1a\x0e.firefly.Empty\"\x00\x12<\n\x0fUpdateNeighbors\x12\x17.firefly.NeighborUpdate\x1a\x0e.firefly.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'simulation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTRATIONREQUEST']._serialized_start=29
  _globals['_REGISTRATIONREQUEST']._serialized_end=78
  _globals['_REGISTRATIONRESPONSE']._serialized_start=80
  _globals['_REGISTRATIONRESPONSE']._serialized_end=172
  _globals['_NEIGHBORUPDATE']._serialized_start=174
  _globals['_NEIGHBORUPDATE']._serialized_end=228
  _globals['_NEIGHBOR']._serialized_start=230
  _globals['_NEIGHBOR']._serialized_end=280
  _globals['_STATUSUPDATE']._serialized_start=282
  _globals['_STATUSUPDATE']._serialized_end=348
  _globals['_FLASHINTERVALREQUEST']._serialized_start=350
  _globals['_FLASHINTERVALREQUEST']._serialized_end=408
  _globals['_EMPTY']._serialized_start=410
  _globals['_EMPTY']._serialized_end=417
  _globals['_OBSERVERSERVICE']._serialized_start=420
  _globals['_OBSERVERSERVICE']._serialized_end=569
  _globals['_FIREFLYSERVICE']._serialized_start=572
  _globals['_FIREFLYSERVICE']._serialized_end=722
# @@protoc_insertion_point(module_scope)
