---
version: "2"
services:
    kafka-1:
        image: confluentinc/cp-kafka:latest
        hostname: kafka-1
        container_name: kafka-1
        ports:
            - 9092:9092
        environment:
            KAFKA_NODE_ID: 1
            KAFKA_PROCESS_ROLES: "broker,controller"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
            KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093"
            KAFKA_LISTENERS: "PLAINTEXT://:19092,CONTROLLER://:9093,PLAINTEXT_HOST://:9092"
            KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:19092,PLAINTEXT_HOST://127.0.0.1:9092
            KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
            CLUSTER_ID: "4L6g3nShT-eMCtK--X86sw"
            KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

            # KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
            # KAFKA_DEFAULT_REPLICATION_FACTOR: 3
            # KAFKA_MIN_INSYNC_REPLICAS: 1

    kafka-2:
        image: confluentinc/cp-kafka:latest
        hostname: kafka-2
        container_name: kafka-2
        ports:
            - 9093:9092
        environment:
            KAFKA_NODE_ID: 2
            KAFKA_PROCESS_ROLES: "broker,controller"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
            KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093"
            KAFKA_LISTENERS: "PLAINTEXT://:19092,CONTROLLER://:9093,PLAINTEXT_HOST://:9092"
            KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:19092,PLAINTEXT_HOST://127.0.0.1:9093
            KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
            CLUSTER_ID: "4L6g3nShT-eMCtK--X86sw"
            KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

            # KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
            # KAFKA_DEFAULT_REPLICATION_FACTOR: 3
            # KAFKA_MIN_INSYNC_REPLICAS: 1

    kafka-3:
        image: confluentinc/cp-kafka:latest
        hostname: kafka-3
        container_name: kafka-3
        ports:
            - 9094:9092
        environment:
            KAFKA_NODE_ID: 3
            KAFKA_PROCESS_ROLES: "broker,controller"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
            KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093"
            KAFKA_LISTENERS: "PLAINTEXT://:19092,CONTROLLER://:9093,PLAINTEXT_HOST://:9092"
            KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:19092,PLAINTEXT_HOST://127.0.0.1:9094
            KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
            CLUSTER_ID: "4L6g3nShT-eMCtK--X86sw"
            KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

            # KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
            # KAFKA_DEFAULT_REPLICATION_FACTOR: 3
            # KAFKA_MIN_INSYNC_REPLICAS: 1
